Flutterando/vaden

README.md

Este PR adiciona a documentação inicial do **VADEN**, um framework backend para Dart inspirado no Spring Boot, focado na experiência do desenvolvedor e segurança robusta.  
- **Introdução ao VADEN**: Explica o propósito do framework e sua inspiração no Spring Boot.  
- **Destaque de funcionalidades**: Lista os principais recursos, como Vaden Security, integração de email e sistema modular de dependências.  
- **Guia de início rápido**: Orientações sobre como criar um projeto usando o Vaden Generator.  
- **Componentes-chave**: Detalha funcionalidades essenciais como autenticação, OAuth2, JWT e integração com Firebase.  
- **Instruções de instalação**: Explicação sobre como adicionar o VADEN ao `pubspec.yaml`.  
- **Comunidade e contribuição**: Links para o Discord e WhatsApp para suporte, …

feat: Readme first update

---

README.md

Corrigi os links das comunidades Flutterando e Dev Ceará no README.md, garantindo que redirecionem corretamente para os respectivos destinos. Essa atualização melhora a experiência do usuário, facilitando o acesso às comunidades mencionadas no projeto.

fix: Fix comunities links

---

vaden/example/lib/src/auth_controller.dart

This PR updates the naming convention for the AuthController in the example folder. It corrects the class and file name to ensure consistency with the project's naming standards.

fix: adjust naming convention for AuthController

---

README.md

Adicionei uma nova sessão para contribuição financeira com o projeto através do apoia.se (<https://apoia.se/vaden>).
Issue: https://github.com/Flutterando/vaden/issues/17

Nova sessão no `README.md` para contribuição financeira com o projeto

---

vaden/lib/src/annotations/annotation.dart
vaden/lib/src/annotations/openapi.dart
vaden/lib/src/annotations/rest.dart
vaden/lib/src/extensions/extensions.dart
vaden/lib/src/extensions/pipeline_extension.dart
vaden/lib/src/middlewares/cors.dart
vaden/lib/src/middlewares/enforce_json_content_type.dart
vaden/lib/src/types/disposable.dart
vaden/lib/src/types/dson.dart
vaden/lib/src/types/guard.dart
vaden/lib/src/types/middleware.dart
vaden/lib/src/types/response_exception.dart
vaden/lib/src/types/validator.dart
vaden/lib/src/utils/app_configuration.dart
vaden/lib/src/utils/openapi_config.dart
vaden/lib/src/utils/resource_service.dart
vaden/lib/src/utils/storage/aws_s3_storage.dart
vaden/lib/src/utils/storage/firebase_storage.dart
vaden/lib/src/utils/storage/local_storage.dart
vaden/lib/src/utils/storage/storage.dart
vaden/lib/vaden.dart

Adiciona a documentação incial do framework

[DOC] Add a initial framwork documentation

---

vaden_generator/backend/assets/dependencies.json
vaden_generator/backend/assets/package_version.json
vaden_generator/backend/lib/config/redis/redis_configuration.dart
vaden_generator/backend/lib/src/core/files/file_manager.dart
vaden_generator/backend/lib/src/core/files/generators/redis.dart
vaden_generator/backend/pubspec.yaml

Adição do Redis dependências do generator

Adição do Redis dependências do generator

---

vaden_generator/backend/assets/dependencies.json
vaden_generator/backend/assets/package_version.json
vaden_generator/backend/lib/src/core/files/file_manager.dart
vaden_generator/backend/lib/src/core/files/generators/postgres.dart
vaden_generator/backend/pubspec.yaml

Adição provisoria do pacote Postgres, para consumo de BD Postgres.

Postgres dependency para generator 

---

vaden_generator/backend/assets/dependencies.json
vaden_generator/backend/lib/src/core/files/file_manager.dart
vaden_generator/backend/lib/src/core/files/generators/cron.dart

Descreva brevemente o que este PR faz e por que ele é necessário.

Cron Dependencies

---

vaden_generator/backend/lib/src/core/files/generators/postgres.dart

Ajuste no Postgres Generator para passar a variável como int na port. 
Resolves #49

Fix bug in  Postgres Generator

---

vaden_class_scanner/lib/src/setups/dto_setup.dart

Ajuste do fronJson no DTO Setup para arrumar o problema do erro ao utilizar lista primitivas dentro dos DTOs

Fix generation the primitive list on dto

---

vaden_generator/backend/assets/metadata.json
vaden_generator/backend/lib/src/controllers/generate_controller.dart
vaden_generator/backend/lib/src/data/services/generate_service_impl.dart
vaden_generator/backend/lib/src/domain/entities/dependency.dart
vaden_generator/backend/lib/src/domain/entities/project_depreciated.dart
vaden_generator/backend/test/src/data/services/generate_service_impl_test.dart

Ajuste no endpoint de criação do generator. 
Resolves #56

Ajuste no endpoint de criação do generator 

---

vaden_generator/frontend/lib/data/repositories/generate_repository.dart
vaden_generator/frontend/lib/data/repositories/remote_generate_repository.dart
vaden_generator/frontend/lib/domain/entities/dart_versions.dart
vaden_generator/frontend/lib/domain/entities/dependency.dart
vaden_generator/frontend/lib/domain/entities/metadata.dart
vaden_generator/frontend/lib/domain/entities/project.dart
vaden_generator/frontend/lib/ui/generate/generate_page.dart
vaden_generator/frontend/lib/ui/generate/viewmodels/generate_viewmodel.dart
vaden_generator/frontend/test/data/mock/response_mock.dart
vaden_generator/frontend/test/data/repositories/remote_generate_repository_test.dart
vaden_generator/frontend/test/ui/generate/viewmodels/generate_viewmodel_test.dart

Ajuste para a utilização das novas rotas feitas no backend.

Ajuste do frontend do generator

---

vaden_generator/backend/lib/src/core/files/generators/cron.dart

Change scheduler import to relative import in cron.dart
this PR fix import because the generator is add import of "teste" projetc, as image:

fix: update import path for cron configuration in CronGenerator

---

vaden/lib/src/annotations/annotation.dart
vaden/lib/src/types/param_parse.dart
vaden/lib/src/types/response_entity.dart
vaden/lib/src/types/response_exception.dart
vaden/lib/src/utils/openapi_config.dart
vaden/lib/src/utils/storage/local_storage.dart

Atualiza a documentacao de alguns modulos

[DOC] Update documentation of Vaden

---

.github/ISSUE_TEMPLATE/1_epic.md
.github/ISSUE_TEMPLATE/2_history.md
.github/ISSUE_TEMPLATE/3_task.md
.github/ISSUE_TEMPLATE/4_bug_report.md
.github/ISSUE_TEMPLATE/5_hotfix.md
.github/ISSUE_TEMPLATE/6_feature_request.md
.github/ISSUE_TEMPLATE/7_question.md
.github/pull_request_template.md

Internacionalização dos template, agora todos os templates do projeto Vaden estão em ingles.
OBS.: Este deve ser o ultimo PR em português 

chore: update issue and pull request templates to English

---

vaden_generator/frontend/lib/i18n/en_US.json
vaden_generator/frontend/lib/ui/core/ui/cards/vaden_card.dart
vaden_generator/frontend/lib/ui/generate/generate_page.dart

Small front adjustments in generator.

fix: small adjustments

---

doc/docs/examples/flutterando-app.md
doc/i18n/pt-BR/docusaurus-plugin-content-docs/current/examples/flutterando-app.md

Adicionado caso de exemplo do Flutterando App na seção de exemplos de casos de uso do Vaden
Resolves #<issue number>

feat: add documentation for the Flutterando application as an example of using Vaden

---

doc/docs/examples/flutterando-app.md
doc/i18n/pt-BR/docusaurus-plugin-content-docs/current/examples/flutterando-app.md
vaden_generator/frontend/lib/i18n/en_US.json
vaden_generator/frontend/lib/ui/core/ui/cards/vaden_card.dart
vaden_generator/frontend/lib/ui/generate/generate_page.dart

Briefly describe what this PR does and why it is necessary.
Resolves #<issue number>

Production

---

vaden_generator/frontend/lib/i18n/en_US.json
vaden_generator/frontend/lib/i18n/es_ES.json
vaden_generator/frontend/lib/i18n/pt_BR.json
vaden_generator/frontend/lib/ui/generate/generate_page.dart

Essa PR implementa um botão para direcionar para a pagina de issues do Vaden, onde o usuario pode reposrtar um problema ou sugerir uma adição de uma nova feature ou etc
Resolves #97

[FEAT] Add button for report problem

---

vaden_generator/backend/assets/dependencies.json
vaden_generator/backend/assets/metadata.json
vaden_generator/backend/lib/src/core/files/generators/email_sendgrid.dart
vaden_generator/backend/lib/src/core/files/generators/otp.dart

This PR introduces two key features to the Generator: integration with a transactional email service (SendGrid) and the implementation of an OTP (One-Time Password) mechanism for secure authentication. These additions are essential to support secure user verification and email delivery capabilities within the system.

Implement Transactional Email via SendGrid and One-Time Password (OTP) Feature
